"""add psu_number to psu

Revision ID: 8dfb9a09aeba
Revises: 840eca6ca908
Create Date: 2025-11-24 09:15:03.728395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dfb9a09aeba'
down_revision: Union[str, Sequence[str], None] = '840eca6ca908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psu', sa.Column('psu_number', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'psu', ['psu_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'psu', type_='unique')
    op.drop_column('psu', 'psu_number')
    # ### end Alembic commands ###
