"""init tables

Revision ID: b1fa526e676e
Revises: 
Create Date: 2025-11-19 16:37:37.356137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1fa526e676e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_psu_email'), 'psu', ['email'], unique=True)
    op.create_index(op.f('ix_psu_id'), 'psu', ['id'], unique=True)
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('iban', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('cash_account_type', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('psu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['psu_id'], ['psu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_id'), 'account', ['id'], unique=False)
    op.create_table('consent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psu_id', sa.Integer(), nullable=False),
    sa.Column('access', sa.JSON(), nullable=True),
    sa.Column('recurring_indicator', sa.Boolean(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('frequency_per_day', sa.Integer(), nullable=True),
    sa.Column('combined_service_indicator', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['psu_id'], ['psu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_id'), 'consent', ['id'], unique=False)
    op.create_table('loan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psu_id', sa.Integer(), nullable=False),
    sa.Column('repayment_account_id', sa.Integer(), nullable=False),
    sa.Column('principal_amount', sa.DECIMAL(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('interest_rate', sa.DECIMAL(), nullable=True),
    sa.Column('term_months', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['psu_id'], ['psu.id'], ),
    sa.ForeignKeyConstraint(['repayment_account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan')
    op.drop_index(op.f('ix_consent_id'), table_name='consent')
    op.drop_table('consent')
    op.drop_index(op.f('ix_account_id'), table_name='account')
    op.drop_table('account')
    op.drop_index(op.f('ix_psu_id'), table_name='psu')
    op.drop_index(op.f('ix_psu_email'), table_name='psu')
    op.drop_table('psu')
    # ### end Alembic commands ###
