"""init

Revision ID: b502226516cd
Revises: b1fa526e676e
Create Date: 2025-11-21 20:58:25.398360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b502226516cd'
down_revision: Union[str, Sequence[str], None] = 'b1fa526e676e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('balance_type', sa.String(), nullable=True),
    sa.Column('amount', sa.DECIMAL(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('reference_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_id'), 'balance', ['id'], unique=True)
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=True),
    sa.Column('booking_date', sa.Date(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.DECIMAL(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('creditor_name', sa.String(), nullable=True),
    sa.Column('debtor_name', sa.String(), nullable=True),
    sa.Column('remittance_information', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_id'), 'transaction', ['id'], unique=True)
    op.create_index(op.f('ix_transaction_transaction_id'), 'transaction', ['transaction_id'], unique=True)
    op.create_table('loan_repayment_schedule_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('principal_due', sa.DECIMAL(), nullable=True),
    sa.Column('interest_due', sa.DECIMAL(), nullable=True),
    sa.Column('total_due', sa.DECIMAL(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_repayment_schedule_item_id'), 'loan_repayment_schedule_item', ['id'], unique=True)
    op.create_unique_constraint(None, 'loan', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loan', type_='unique')
    op.drop_index(op.f('ix_loan_repayment_schedule_item_id'), table_name='loan_repayment_schedule_item')
    op.drop_table('loan_repayment_schedule_item')
    op.drop_index(op.f('ix_transaction_transaction_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_balance_id'), table_name='balance')
    op.drop_table('balance')
    # ### end Alembic commands ###
