"""init

Revision ID: ebcc45cb6ed7
Revises: 2d7a496604e2
Create Date: 2025-11-22 10:51:41.005692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebcc45cb6ed7'
down_revision: Union[str, Sequence[str], None] = '2d7a496604e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_transaction_id'), table_name='transaction')
    op.drop_column('transaction', 'transaction_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('transaction_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_transaction_transaction_id'), 'transaction', ['transaction_id'], unique=True)
    # ### end Alembic commands ###
